# Generated by Django 4.2.6 on 2023-10-25 07:45

import Calgen.utils.configs
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Calgen", "0002_filemanager_created_at_filemanager_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filemanager",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="filemanager",
            name="upload",
            field=models.FileField(
                storage=Calgen.utils.configs.OverwriteStorage(),
                upload_to=Calgen.utils.configs.upload_config,
            ),
        ),
    ]
